stages:
  load_data: 
    cmd: python src/load_data.py --config=params.yaml
    deps:
      - src/get_data.py
      - src/load_data.py
      - source_data/EHR.csv

    outs:
      - data/raw/EHR_processed.yaml

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
      - src/split_data.py
      - data/raw/EHR_processed.yaml

    outs:
      - data/processed/train_EHR.csv
      - data/processed/test_EHR.csv
  
  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps:
      - data/processed/train_EHR.csv
      - data/processed/test_EHR.csv
      - src/train_and_evaluate.py

    params:
      - estimators.ElasticNet.params.alpha
      - estimators.ElasticNet.params.l1_ratio

    metrics:
      - reports/scores.json
        cache: false
      - reports/params.json
        cache: false
    outs:
      - models/model.joblib